### ISSUE TITLE
Field 'background' missing in 'Text'

### ISSUE THREAD

**Issue by bombedhair** [tgyuuAn/SWM-ServerDriven-AOS#14]
`api.swm-mobile.org/richtext.json` 응답의 `$.responseData.contents[?(@.viewType == "RichViewType")].content.richText` 중
```json
{
    "text": {
        "text": "Rich Text",
        "background": "yellow",
        "fontSize": 24
    }
}
```
배경 색을 나타내는 `background` 필드가 존재하는 항목이 있는데, `Text`에는 해당 필드가 존재하지 않습니다.

제가 지난 주 클래스를 화상으로 들었다보니 제가 놓친 스펙 변경이 있었던 것인지, 혹은 누락된 것인지 몰라 일단 `question` 레이블로 남깁니다. 필요 시 레이블 변경을 부탁드립니다.

**Comment by tgyuuAn** [comment]
그러게요! `background` 속성이 있네욥.

@jung0115 @Seungman-dev 보시면 확인 부탁드립니닷
